{"task_id": 94, "prediction_id": 0, "generation": "def iter_all(class_name):\n    \"\"\"Iterate over all objects of the same class by its class name\"\"\"\n    for obj in live_refs[class_name].values():\n        yield obj\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 87, in <module>\n  File \"<string>\", line 86, in test_59\nAssertionError\n", "passed": false}
{"task_id": 94, "prediction_id": 1, "generation": "def iter_all(class_name):\n    \"\"\"Iterate over all objects of the same class by its class name\"\"\"\n    for obj in live_refs[class_name].values():\n        yield obj\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 87, in <module>\n  File \"<string>\", line 86, in test_59\nAssertionError\n", "passed": false}
{"task_id": 94, "prediction_id": 2, "generation": "def iter_all(class_name):\n    \"\"\"Iterate over all objects of the same class by its class name\"\"\"\n    for obj in live_refs[class_name].values():\n        yield obj\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 87, in <module>\n  File \"<string>\", line 86, in test_59\nAssertionError\n", "passed": false}
{"task_id": 94, "prediction_id": 3, "generation": "def iter_all(class_name):\n    \"\"\"Iterate over all objects of the same class by its class name\"\"\"\n    for obj in live_refs[class_name].values():\n        yield obj\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 87, in <module>\n  File \"<string>\", line 86, in test_59\nAssertionError\n", "passed": false}
{"task_id": 94, "prediction_id": 4, "generation": "def iter_all(class_name):\n    \"\"\"Iterate over all objects of the same class by its class name\"\"\"\n    for obj in live_refs[class_name].values():\n        yield obj\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 87, in <module>\n  File \"<string>\", line 86, in test_59\nAssertionError\n", "passed": false}
{"task_id": 94, "prediction_id": 5, "generation": "def iter_all(class_name):\n    \"\"\"Iterate over all objects of the same class by its class name\"\"\"\n    for obj in live_refs[class_name].values():\n        yield obj\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 87, in <module>\n  File \"<string>\", line 86, in test_59\nAssertionError\n", "passed": false}
{"task_id": 94, "prediction_id": 6, "generation": "def iter_all(class_name):\n    \"\"\"Iterate over all objects of the same class by its class name\"\"\"\n    for obj in live_refs[class_name].values():\n        yield obj\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 87, in <module>\n  File \"<string>\", line 86, in test_59\nAssertionError\n", "passed": false}
{"task_id": 94, "prediction_id": 7, "generation": "def iter_all(class_name):\n    \"\"\"Iterate over all objects of the same class by its class name\"\"\"\n    for obj in live_refs[class_name].values():\n        yield obj\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 87, in <module>\n  File \"<string>\", line 86, in test_59\nAssertionError\n", "passed": false}
{"task_id": 94, "prediction_id": 8, "generation": "def iter_all(class_name):\n    \"\"\"Iterate over all objects of the same class by its class name\"\"\"\n    for obj in live_refs[class_name].values():\n        yield obj\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 87, in <module>\n  File \"<string>\", line 86, in test_59\nAssertionError\n", "passed": false}
{"task_id": 94, "prediction_id": 9, "generation": "def iter_all(class_name):\n    \"\"\"Iterate over all objects of the same class by its class name\"\"\"\n    for obj in live_refs[class_name].values():\n        yield obj\n", "message": "failed: Traceback (most recent call last):\n  File \"/codegendata/human-eval/human_eval/execution.py\", line 57, in unsafe_execute\n    exec(check_program, exec_globals)\n  File \"<string>\", line 87, in <module>\n  File \"<string>\", line 86, in test_59\nAssertionError\n", "passed": false}
